### ISSUE TITLE
Add Azure AKS support

### ISSUE THREAD

**Issue by velvia** [Dentrax/kubesql#1]
This is an awesome project!   Would love if azure support could be added.  If I had lots of time could potentially help here.
```
thread 'main' panicked at 'an error occurred during creating kube client: failed to create the kube client with context

Caused by:
    0: Error loading kubeconfig: Failed exec auth: Authentication with provider azure not supported
    1: Failed exec auth: Authentication with provider azure not supported

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
      std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
      std::backtrace::Backtrace::create
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/backtrace.rs:327:13
   1: std::backtrace::Backtrace::capture
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/backtrace.rs:295:9
   2: kubesql::main::{{closure}}
   3: tokio::park::thread::CachedParkThread::block_on
   4: tokio::runtime::thread_pool::ThreadPool::block_on
   5: tokio::runtime::Runtime::block_on
   6: kubesql::main
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
   8: std::rt::lang_start::{{closure}}
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:379:40
      std::panicking::try

```

**Comment by Dentrax** [comment]
Hey @velvia, I'm glad you like it. I think It is a known issue of the underlying lib used to communicate with K8s. Could you please check this issue out? https://github.com/clux/kube-rs/issues/238

**Comment by velvia** [comment]
Hmmm… it’s not clear to me, that issue was closed, does it mean it is now resolved?

**Comment by Dentrax** [comment]
I'm not sure exactly, but maybe you did misconfigure your kubeconfig?

**Comment by velvia** [comment]
No it’s not the kubeconfig, the exception clearly states that azure authentication is not yet supported.

**Comment by Dentrax** [comment]
Hey @clux, sorry for pinging, have you any ideas here? Azure auth method is [falling this line](https://github.com/clux/kube-rs/blob/1af2827be30127f5bc280a182b1bcdc620059587/kube/src/service/auth/mod.rs#L175), I guess. Have you any idea why azure is [commented out](https://github.com/clux/kube-rs/blob/1af2827be30127f5bc280a182b1bcdc620059587/kube/src/service/auth/mod.rs#L168)?

**Comment by clux** [comment]
Ah, I think that might be due to a bigger refactor around oauth, sorry :(

We never technically implemented the auth providers right until recently, but I guess it kind of worked anyway. I have opened an issue on our end. Thanks for the heads up.

You can [bypass](https://clux.github.io/probes/post/2019-03-31-impersonating-kube-accounts/) oauth flow by doing service-account style auth. Maybe that's why people have not complained before :thinking:
